import ply.lex as lex

tokens = ('PROGRAM', 'TXT', 'DUMBO_BLOCK', 'EXPRESSIONS_LIST', 'EXPRESSION', 'STRING_EXPRESSION', 'STRING_LIST', 'STRING_LIST_INTERIOR', 'VARIABLE', 'STRING', 'PIPE', 'HOOK_OPEN', 'HOOK_CLOSE', 'SEMICOLON', 'PRINT', 'FOR', 'IN', 'DO', 'ENDFOR', 'EQUALS', 'DOT', 'COMA', 'PARENTHESIS_OPEN', 'PARENTHESIS_CLOSE')
